

# app:
  # hostname: 0.0.0.0
  # port: 2875
  # database_url: postgres://autopulse:autopulse@localhost:5432/autopulse

# auth:
  # username: admin
  # password: password

# opts:
  # check_path: true # Check if the path exists, assuming the path is available to the container
  # max_retries: 5 # Exponential backoff when a target fails

# triggers:
  # sonarr:
  #   type: sonarr
  #   rewrite:
  #     from: /orig/tv
  #     to: /new/tv
  
# webhooks:
  # discord:
  #   type: "discord"
  #   url: "https://discord.com/api/webhooks/1234567890/aBcDeFgHiJkLmNoPqRsTuVwXyZ"

# targets:
  # plex:
  #   type: plex
  #   url: http://plex:32400
  #   token: your-plex-token

  # jellyfin:
  #   type: jellyfin
  #   url: http://jellyfin:8096
  #   token: your-jellyfin-token

  # list:
  #   type: command
    # raw: echo $FILE_PATH >> list.txt
    # or
    # path: /path/to/script.sh
