version: '3'

services:
  autopulse:
    image: danonline/autopulse
    container_name: autopulse
    restart: always
    depends_on:
      - postgres
    ports:
      - 2875:2875
    networks:
      - db
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
       AUTOPULSE__APP__DATABASE_URL: postgres://autopulse:autopulse@postgres/autopulse
      
  postgres:
    image: postgres:alpine
    container_name: autopulse-postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - db
    environment:
      POSTGRES_USER: autopulse
      POSTGRES_PASSWORD: autopulse
      POSTGRES_DB: autopulse
  
networks:
  db:
    driver: bridge