hostname = "0.0.0.0"
port = 2875
username = "admin"
password = "password"
database_url = "postgres://test:test@localhost:5432/autopulse"

check_path = true
max_retries = 3

[triggers.manual]
type = "manual"

[targets]

[webhooks]
