name: Cleanup Pull Request

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: number

jobs:
  merge_job:
    runs-on: self-hosted
    steps:
      - name: Remove tag
        run: |
          if [ -n "${{ github.event.inputs.pr_number }}" ]; then
            pr_number="${{ github.event.inputs.pr_number }}"
          else
            pr_number="${{ github.event.number }}"
          fi
          docker run --rm lumir/remove-dockerhub-tag --user ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }} danonline/autopulse:pr-${pr_number} || true
